changelog:
  exclude:
    labels:
      - renovate
      - tagpr
      - maintenance
      - chore
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major
    - title: New features
      labels:
        - enhancement
        - minor
    - title: Bug fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
